### ISSUE TITLE
Look into mapping SDG to CRS categories when PoolParty is installed

### ISSUE THREAD

**Issue by dw8547** [devinit/ddw#28]
Following the DAC Working Party on Development Finance Statistics "Comprehensive review of purpose codes and policy makers in light of the SDGS and post 2015 agenda".

SDG = Sustainable Development Goals?
SDG = Strategic Decision Group?

Link to document: http://www.oecd.org/officialdocuments/publicdisplaydocumentpdf/?cote=DCD/DAC/STAT%282015%299&docLanguage=En.

Bill needs to explain.

**Comment by dw8547** [comment]
Transferring ownership of this issue to the PP team (@lisssek). Will duplicate the issue in the relevant repository.

**Comment by lisssek** [comment]
I am not sure if this is still an open problem but the SDG stand for Sustainable Development Goals. The OECD DAC CRS sectors do not alight well with the SDGs which might mean that some goals might not be financed properly. Does that answer the question? Is it even still relevant? Sorry for the late reply.

**Comment by Duncan-Knox** [comment]
Just received email on this, and thought it may be worth writing a quick note as some of my work arguably overlaps with this. Broadly speaking, a number of the SDGs can be mapped onto CRS fields, particularly sectors, purpose codes and policy markers:

e.g. some examples based on 17 SGDs:
-**Food** to emergency food aid, food security, basic nutrition and relevant agricultural purpose codes
-**Health** to health sectors (health and population policies & reproductive health)
-**Education** - education sector
- **Energy** - energy sector
- **Water** - WASH sector and other relevant purpose codes
-**Ecosystems **- relevant purpose codes (bio-diversity), plus other purpose codes under general environmental protection(?) and policy marker biodiversity.
-** Climate **- climate change rio-policy markers

Whilst others such as: Inequality, sustainability and poverty are broader and likely difficult to comprehensively map onto specific CRS fields. 

I hope this may be of help!

**Comment by lisssek** [comment]
Actually I think we might be able to help you Duncan! We have mapped SDG targets to CRS, COFOG, MDGs, WDI and word themes and sectors!

**Comment by Duncan-Knox** [comment]
Thanks for the reply, this sounds interesting, is it possible to see the details?

**Comment by lisssek** [comment]
the chords are available in our report and the hands on mapping can be accessed through joinedupdata.org  I will send you a manual to make things a bit clearer! Thanks for the info Duncan!

**Comment by Duncan-Knox** [comment]
Great, thanks!

**Comment by lisssek** [comment]
my pleasure!

**Comment by dw8547** [comment]
Hi @lisssek & @Duncan-Knox. This is something that @bill-anderson wanted to do once PoolParty was installed. He will have more details.
