### ISSUE TITLE
Bad RIP Value OS Crash

### ISSUE THREAD

**Issue by dw8547** [devinit/ddw#60]
The DELL XPS-15-9530 & Ubuntu 15.04 crash when powering off with a "Bad RIP Value". The only way that I can get out of the crash is by "REISUB" (rebooting even if system utterly broken). This happens almost everyday. I have no idea why. @leightonjames, would you be able to help please? I'm concerned that the DELL XPS-15-9530 might give up the ghost and take the development server with it (in which case I'm in trouble). I have attached a screenshot of what the crash looks like. The only way to get past this stage is to force quit/reboot.
![20151023_155704](https://cloud.githubusercontent.com/assets/10259585/10770414/12c603f0-7ce3-11e5-8400-7879c49e2a39.jpg)

**Comment by leightonjames** [comment]
Hi @dw8547 Please can you show me this issue next time you are in the office? Could be a hardware issue or perhaps the ubuntu install? Can we take a backup of your development server and investigate further?

**Comment by dw8547** [comment]
@leightonjames, will do both. Thank you!

**Comment by dw8547** [comment]
@leightonjames, I'm going to try this to see if it helps:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/528720/comments/6
Full thread:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/528720

**Comment by dw8547** [comment]
Dell has been repaired (screen) and rebuilt. This is (hopefully) no longer valid.
